apiVersion: v1
kind: Service
metadata:
  name: argo-app-service
spec:
  selector:
    app: argo-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
  type: NodePort

  