name: Test and Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker tag
        id: version
        run: |
          echo "VERSION=v$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build . -t hirudoc5/argo-app:${{ env.VERSION }}

      - name: Push Docker Image
        run: |
          docker push hirudoc5/argo-app:${{ env.VERSION }}

      - name: Update K8s Manifests
        run: |
          sed -i "s|image: hirudoc5/argo-app:.*|image: hirudoc5/argo-app:${{ env.VERSION }}|g" deploy/deploy.yaml
          cat deploy/deploy.yaml

      - name: Commit the changes
        run: |
          git config --global user.email "hirushafernando121@gmail.com"
          git config --global user.name "Hirusha1-cpu"
          git add deploy/deploy.yaml
          git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/Hirusha1-cpu/argo_cd_project.git
          git push origin master
